service:
  name: wcmui3
plugins:
  - serverless-python-requirements
  #- serverless-domain-manager
provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sts:AssumeRole
      Resource: "*"

  memorySize: 1024
  timeout: 30
  versionFunctions: false
  reservedConcurrency: 5
  logRetentionInDays: 30


custom:
  appName: wcmui2


  pythonRequirements:
    slim: true
    dockerizePip: non-linux


package:
  individually: true

resources:
  - ${file(resources/s3.yaml)}
  - ${file(resources/cloudFront.yaml)}


functions:
  test:
    handler: functions/test_lambda.lambda_handler
    package:
      include:
        - functions/**
    events:
      - http:
          path: /api/test
          method: GET
          cors: true




