Resources:
  ApiCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: "http2"
        Origins:
          # I belive the problem is here
          - DomainName:
              Fn::Join:
                - ""
                - - ""
                  - Ref: ApiGatewayRestApi
                  - ".execute-api.${opt:region, self:provider.region}.amazonaws.com"
            OriginPath: "/${self:provider.stage}"
            Id: "lambdaid=${self:provider.stage}-${self:service}"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: 'true'
#        Aliases:
#          - "api-${self:provider.stage}-${self:service}.com"
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT

          MaxTTL: 0
          DefaultTTL: 0
          ## The origin id defined above
          TargetOriginId: "lambdaid=${self:provider.stage}-${self:service}"
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ## The certificate to use when viewers use HTTPS to request objects.
  #          ViewerCertificate:
  #            AcmCertificateArn: "arn:aws:acm:us-east-1:<MY ACCOUNT>:certificate/<MY CERTIFICATE>"
  #            SslSupportMethod: sni-only
  #            MinimumProtocolVersion: TLSv1.1_2016
  #          Logging:
  #            IncludeCookies: 'false'
  #            Bucket: "<MY BUCKET>.s3.amazonaws.com"
  #            Prefix: "api-${self:provider.stage}-${self:service}"