Resources:
  ApiCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: "http2"
        DefaultRootObject: index.html
        Origins:
          # I belive the problem is here
          - DomainName:
              Fn::Join:
                - ""
                - - ""
                  - Ref: ApiGatewayRestApi
                  - ".execute-api.${opt:region, self:provider.region}.amazonaws.com"
            OriginPath: "/${self:provider.stage}"
            Id: "lambdaid=${self:provider.stage}-${self:service}"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only

          - DomainName: #define the s3 origin
              Fn::GetAtt: [ S3BucketWCMUI , "DomainName" ]
            Id: webpage
            OriginPath: 'v1.0'
            S3OriginConfig:
              OriginAccessIdentity:
                Ref: AWS::NoValue


        Enabled: 'true'
#        Aliases:
#          - "api-${self:provider.stage}-${self:service}.com"
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT

          MaxTTL: 0
          DefaultTTL: 0
          ## The origin id defined above
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: 'webpage' #id of the orignin

        CacheBehaviors: #second the behavior for the API Gateway
          - AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT

            MaxTTL: 0
            DefaultTTL: 0
            ## The origin id defined above
            Compress: true
            ForwardedValues:
#              Headers: #define explicit headers, since API Gateway doesn't work otherwise
#                - Accept
#                - Referer
#                - Athorization
#                - Content-Type
              QueryString: true #to transfer get parameters to the gateway
            PathPattern: "/api/*" #path pattern after the Gateway stage identifier.
            TargetOriginId: 'lambdaid=${self:provider.stage}-${self:service}' #id of the orignin
            ViewerProtocolPolicy: redirect-to-https #API Gateway only support https


        ## The certificate to use when viewers use HTTPS to request objects.
  #          ViewerCertificate:
  #            AcmCertificateArn: "arn:aws:acm:us-east-1:<MY ACCOUNT>:certificate/<MY CERTIFICATE>"
  #            SslSupportMethod: sni-only
  #            MinimumProtocolVersion: TLSv1.1_2016
  #          Logging:
  #            IncludeCookies: 'false'
  #            Bucket: "<MY BUCKET>.s3.amazonaws.com"
  #            Prefix: "api-${self:provider.stage}-${self:service}"